### ISSUE TITLE
Installing from Local Drive: error unable to read from setup package!.

### ISSUE THREAD

**Issue by Wormi83** [soner-boztas/installforge#1]
**Description**
Installing from Local Drive: error unable to read from setup package!.

**Environment**
InstallForge version: 1.4.4.22
Windows 11/Windows 10, either or/both

**Steps to Reproduce**
1. Go to 'build MyInstall,exe'
2. Run 'MyInstall.exe' once built

**Observed Behavior**
When running a created install, randomly a user will get error unable to read from setup package!.
I say randomly because I cannot for the life of me re-create it with any consistency, sometimes I will get the error, have someone else open it and it will work fine for them. then if i just rebuild it with the exact same files it might be visa versa.
Sometimes I can make the package readable by simpyl copy/pasting it into the same location and the running .(copy).exe will work, sometimes it wont.

**Expected Behavior**
Install runs as it does without the error.

**Screenshots**

**Comment by Wormi83** [comment]
Forgot to add step 2 is rename MyInstall.exe to MyInstallRelease10.74.exe
Where 10.74 could be anything xx.xx

**Comment by Wormi83** [comment]
Also forgot to add signed executable with signtool however it seems to do this if I sign it or not.

**Comment by soner-boztas** [comment]
Thanks for this report. This issue also happens occasionally for other users. The fact that it happens somehow non-deterministic makes technical investigations from my end very hard.

Could you verify that - after this issue happens - the SHA hash of the executable does not change?

**Comment by Wormi83** [comment]
[image: image.png]

Actual Hash of another file which works for nearly everyone except a couple
of users.
[image: image.png]

**Comment by muhamedRadwan** [comment]
this happened to my users and was solved by closing Windows Defender 
also windows defender show my app is virus Trojan:Script/Wacatac.H!ml

**Comment by Wormi83** [comment]
Possible Fix @soner-boztas I was still having the random unable to read from setup package! But I released a new version and changed the compression from the default, to the second option (can't recall named off top of my head something with a 2 in it) and since, Have had no reports of the unable to read setup package error.

**Comment by Wormi83** [comment]
Possible Fix @soner-boztas <https://github.com/soner-boztas> I was still
having the random unable to read from setup package! But I released a new
version and changed the compression from the default, to the second option
(can't recall named off top of my head something with a 2 in it) and since,
Have had no reports of the unable to read setup package error.

**Comment by SmartBaby626** [comment]
Wait nvm its stopped working again
